name: Readme Projects Display
author: Kaustubh Gupta  
description: Updates Readme/specified file with latest projects information
inputs:
  gh_token:
    description: "Github Personal Access token"
    required: True
  readme_path:
    description: "Path of the file"
    required: False
    default: README.md
runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub
      shell: bash
    - run: ${{ github.action_path }}/main-script.py ${{ inputs.gh_token }} ${{ inputs.readme_path }}
      shell: python
branding:
  icon: "award"
  color: "blue"
