name: Readme Projects Display
author: Kaustubh Gupta  
description: Updates Readme/specified file with latest projects information
inputs:
  gh_token:
    description: "Github Personal Access token"
    required: True
  file_name:
    description: "Name of the file"
    required: False
    default: README.md

runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub
      shell: bash
    - run: python ${{ github.action_path }}/main-script.py ${{ inputs.gh_token }} ${{ inputs.file_name }} ${{ github.workspace }}
      shell: bash
branding:
  icon: "award"
  color: "blue"
