name: Readme Projects Display
author: Kaustubh Gupta  
description: Updates Readme/specified file with latest projects information
inputs:
  gh_token:
    description: "Github Personal Access token"
    required: True
  file_name:
    description: "Name of the file"
    required: False
    default: README.md
  max_repo_description:
    description: "How much description you want to Display"
    required: False
    default: 50
  allow_forks:
    description: "Control if you want forks count"
    required: False
    default: True

runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub
      shell: bash
    - run: python ${{ github.action_path }}/main-script.py ${{ inputs.gh_token }} ${{ inputs.file_name }} ${{ github.workspace }} ${{ inputs.max_repo_description }} ${{ inputs.allow_forks }}
      shell: bash
branding:
  icon: "award"
  color: "blue"
